# Generated by Django 5.1.4 on 2025-01-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_date_lesson_scheduled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='lessons_completed',
            field=models.ManyToManyField(blank=True, to='accounts.lesson'),
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
    ]
